<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260226203500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create portfolio valuation snapshots table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE portfolio_valuation_snapshots (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, calculated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, amount_usdt NUMERIC(20, 2) NOT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE portfolio_valuation_snapshots');
    }
}
